#!/bin/bash


while read -a line
do
	core=${line[3]}
	version=${core##*/}
	export conf=piraten$( echo ${line[0]} | sed -e  's/\//-/g')
	export line

	su - www-data --preserve-environment -c "(cd ${line[2]} && echo 'Event:send_notifications_loop()' | ${line[4]}/bin/webmcp_shell $conf & ) "
	sleep 5
done < /opt/lqfb/instances

